spring:
  datasource:
    url: jdbc:postgresql://192.168.192.5:5432/tormozzg
    username: tormozzg
    password: tormozzg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
info:
  app:
    version: 1.0.0

---
spring:
  profiles: test
  datasource:
    schema: test
    url: jdbc:postgresql://192.168.192.5:5432/tormozzg
    username: tormozzg
    password: tormozzg
    driver-class-name: org.postgresql.Driver